MinhaAppMvcDesafio/Controllers/FornecedorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MinhaAppMvcDesafio.Models;
using MinhaAppMvcDesafio.Repositories.Interfaces;
using MinhaAppMvcDesafio.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MinhaAppMvcDesafio.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly IFornecedorRepository _fornecedorRepository;
        private readonly IMapper _mapper;
        private const int _paginaInicial = 110;

        public FornecedorController(IFornecedorRepository fornecedorRepository, IMapper mapper)
        {
            _fornecedorRepository = fornecedorRepository;
            _mapper = mapper;
        }

        [Route("lista-fornecedores/{pagina:int}")]
        public async Task<IActionResult> Index(int pagina = 1)
        {
            ViewData["Titulo"]     = "Lista de Fornecedores";
            ViewData["Acao"]       = "";
            ViewData["Pagina"]     = pagina.ToString();
            // Posição do campo: dezena do valor do parâmetro
            ViewData["OrdCampo"] = pagina.ToString().Substring(pagina.ToString().Length - 2, 1);
            // Sentido do campo: unidade do valor do parâmetro
            ViewData["OrdSentido"] = pagina.ToString().Substring(pagina.ToString().Length - 1, 1);
            ViewData["QtdPaginas"] = _fornecedorRepository.ObterQtdPaginas().ToString();
            return View(_mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterPaginados(pagina)));
        }
        //public JsonResult Listar(int pagina = 1, int registros = 5)
        //{
        //    var lista = _mapper.Map<IEnumerable<FornecedorViewModel>>(_fornecedorRepository.ObterTodos());
        //    lista = lista.Skip((pagina - 1) * registros).Take(registros);
        //    return Json(lista);
        //}

        [Route("dados-fornecedor/{id:int}")]
        public async Task<IActionResult> Cadastro(int id = 0)
        {
            var fornecedor = new FornecedorViewModel();
            if (id != 0)
            {
                fornecedor = await ObterFornecedorEndereco(id);
                if (fornecedor == null) return NotFound();
            }
            ViewData["Titulo"] = "Cadastro de Fornecedores";
            ViewData["Id"] = id.ToString();
            return View(fornecedor);
        }

        [Route("salvar-fornecedor")]
        [HttpPost]
        public async Task<IActionResult> Salvar(FornecedorViewModel fornecedorViewModel)
        {
            int id = int.Parse(Request.Form["Id"].ToString());
            if (id != 0 && id != fornecedorViewModel.Id) return NotFound();
            if (!ModelState.IsValid) return View(fornecedorViewModel);
            var fornecedor = _mapper.Map<Fornecedor>(fornecedorViewModel);
            if (id == 0)
                await _fornecedorRepository.Adicionar(fornecedor);
            else
                await _fornecedorRepository.Atualizar(fornecedor);
            //if (!OperacaoValida()) return View(fornecedorViewModel);
            //if (!OperacaoValida()) return View(await ObterFornecedorProdutosEndereco(id));
            ViewData["Acao"] = "S";
            ViewBag.Acao = "S";
            return RedirectToAction("Index", new { pagina = _paginaInicial });
        }

        [Route("excluir-fornecedor/{id:int}")]
        public async Task<IActionResult> Excluir(int id)
        {
            var fornecedor = await ObterFornecedorEndereco(id);
            if (fornecedor == null) return NotFound();
            await _fornecedorRepository.Remover(id);
            //if (!OperacaoValida()) return View(fornecedor);
            ViewData["Acao"] = "E";
            return RedirectToAction("Index", new { pagina = _paginaInicial });
        }

        private async Task<FornecedorViewModel> ObterFornecedorEndereco(int id)
        {
            return _mapper.Map<FornecedorViewModel>(await _fornecedorRepository.ObterFornecedorEndereco(id));
        }

        private async Task<FornecedorViewModel> ObterFornecedorProdutosEndereco(int id)
        {
            return _mapper.Map<FornecedorViewModel>(await _fornecedorRepository.ObterFornecedorProdutosEndereco(id));
        }
    }
}

MinhaAppMvcDesafio/Controllers/ProdutoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MinhaAppMvcDesafio.Models;
using MinhaAppMvcDesafio.Repositories.Interfaces;
using MinhaAppMvcDesafio.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;

namespace MinhaAppMvcDesafio.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly IFornecedorRepository _fornecedorRepository;
        private readonly IMapper _mapper;
        private const int _paginaInicial = 110;

        public ProdutoController(IProdutoRepository produtoRepository, IFornecedorRepository fornecedorRepository, IMapper mapper)
        {
            _produtoRepository = produtoRepository;
            _fornecedorRepository = fornecedorRepository;
            _mapper = mapper;
        }

        [Route("lista-produtos/{pagina:int}")]
        public async Task<IActionResult> Index(int pagina = _paginaInicial)
        {
            ViewData["Titulo"]     = "Lista de Produtos";
            ViewData["Acao"]       = "";
            ViewData["Pagina"]     = pagina.ToString();
            // Posição do campo: dezena do valor do parâmetro
            ViewData["OrdCampo"]   = pagina.ToString().Substring(pagina.ToString().Length - 2, 1);
            // Sentido do campo: unidade do valor do parâmetro
            ViewData["OrdSentido"] = pagina.ToString().Substring(pagina.ToString().Length - 1, 1);  
            ViewData["QtdPaginas"] = _produtoRepository.ObterQtdPaginas().ToString();
            return View(_mapper.Map<IEnumerable<ProdutoViewModel>>(await _produtoRepository.ObterPaginados(pagina)));
        }

        [Route("dados-produto/{id:int}")]
        public async Task<IActionResult> Cadastro(int id = 0)
        {
            var produto = new ProdutoViewModel();
            string fornecedorId = "";
            ViewData["NomeImagem"] = "";
            if (id != 0)
            {
                produto = await ObterProdutoFornecedor(id);
                if (produto == null) return NotFound();
                fornecedorId = produto.FornecedorId.ToString();
                if (!string.IsNullOrEmpty(produto.Imagem))
                    ViewData["NomeImagem"] = produto.Imagem.Split("_")[1].ToUpper(); // obtém apenas o nome físico do arquivo, após o "_"
            }
            ViewData["Titulo"] = "Cadastro de Produtos";
            ViewData["Id"] = id.ToString();
            ViewData["ComboFornecedores"] = ComboFornecedores(fornecedorId);
            return View(produto);
        }

        public string ComboFornecedores(string id = "")
        {
            string resultado = "";
            Task<List<Fornecedor>> itens = _fornecedorRepository.ObterTodos();
            if (itens == null) return "";
            foreach (var item in itens.Result)
            {
                string vChecked = (item.Id.ToString() == id ? " selected" : "");
                resultado += "<option value='" + item.Id.ToString() + "'" + vChecked + ">" + item.Nome.ToUpper() + "</option>";
            }
            return resultado;
        }

        [Route("salvar-cadastro")]
        [HttpPost]
        public async Task<IActionResult> Salvar(ProdutoViewModel produtoViewModel)
        {
            produtoViewModel.Valor /= 100;  // Essa divisão serve para evidenciar a parte decimal do valor
            int id = int.Parse(Request.Form["Id"].ToString());
            if (id != 0 && id != produtoViewModel.Id) return NotFound();
            if (!ModelState.IsValid) return View(produtoViewModel);
            var produto = _mapper.Map<Produto>(produtoViewModel);
            if (produtoViewModel.ImagemUpload != null)
            {
                var imgPrefixo = DateTime.Now.ToString("yyyyMMddHHmmss") + "_";
                if (!await UploadArquivo(produtoViewModel.ImagemUpload, imgPrefixo))
                    return View(produtoViewModel);
                produto.Imagem = imgPrefixo + produtoViewModel.ImagemUpload.FileName;
            }
            if (id == 0)
                await _produtoRepository.Adicionar(produto);
            else
                await _produtoRepository.Atualizar(produto);
            ViewData["Acao"] = "S";
            ViewBag.Acao = "S";
            return RedirectToAction("Index", new { pagina = _paginaInicial });
        }

        private async Task<bool> UploadArquivo(IFormFile arquivo, string imgPrefixo)
        {
            if (arquivo.Length <= 0) return false;
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/imagens/produtos", imgPrefixo + arquivo.FileName);
            if (System.IO.File.Exists(path))
            {
                ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome!");
                return false;
            }
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await arquivo.CopyToAsync(stream);
            }
            return true;
        }

        [Route("excluir-produto/{id:int}")]
        public async Task<IActionResult> Excluir(int id)
        {
            var produto = await ObterProdutoFornecedor(id);
            if (produto == null) return NotFound();
            await _produtoRepository.Remover(id);
            ViewData["Acao"] = "E";
            return RedirectToAction("Index", new { pagina = _paginaInicial });
        }

        private async Task<ProdutoViewModel> ObterProdutoFornecedor(int id)
        {
            return _mapper.Map<ProdutoViewModel>(await _produtoRepository.ObterProdutoFornecedor(id));
        }

        //[Route("movimentacao-estoque/{pagina:int}")]
        //public async Task<IActionResult> MovimentacaoEstoque(int pagina = _paginaInicial)
        //{
        //    ViewData["Titulo"] = "Movimentação de Estoque";
        //    ViewData["Pagina"] = pagina.ToString();
        //    // Posição do campo: dezena do valor do parâmetro
        //    ViewData["OrdCampo"] = pagina.ToString().Substring(pagina.ToString().Length - 2, 1);
        //    // Sentido do campo: unidade do valor do parâmetro
        //    ViewData["OrdSentido"] = pagina.ToString().Substring(pagina.ToString().Length - 1, 1);
        //    ViewData["QtdPaginas"] = _produtoRepository.ObterQtdPaginas().ToString();
        //    return View("MovimentacaoEstoque", _mapper.Map<IEnumerable<EstoqueViewModel>>(await _produtoRepository.MovimentacaoEstoque(1, pagina)));
        //}
    }
}

MinhaAppMvcDesafio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MinhaAppMvcDesafio</title>
    <script src="~/js/jquery331.min.js"></script>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/bootstrap431.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        .divPaginacao {
            text-align: center;
        }

        .pagination {
            display: inline-block;
        }

            .pagination a {
                color: black;
                float: left;
                padding: 8px 12px;
                text-decoration: none;
                transition: background-color .3s;
                border: 1px solid #ddd;
                margin: 0 0px;
                font-family: Arial;
                font-size: 12px;
            }

                .pagination a.active {
                    background-color: #000000;
                    color: white;
                    border: 1px solid #000000;
                    font-weight: bold;
                }

                .pagination a:hover:not(.active) {
                    background-color: #ddd;
                }

                .pagination a:first-child {
                    border-top-left-radius: 5px;
                    border-bottom-left-radius: 5px;
                }

                .pagination a:last-child {
                    border-top-right-radius: 5px;
                    border-bottom-right-radius: 5px;
                }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Principal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index" asp-route-pagina="110">Fornecedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index" asp-route-pagina="110">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index" asp-route-pagina="110">Pedidos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estoque" asp-action="MovimentacaoEstoque">Movimentação de Estoque</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MinhaAppMvcDesafio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/jquery331.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="~/js/bootstrap431.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>